// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://spizfutrtikunxjbaexy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNwaXpmdXRydGlrdW54amJhZXh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MTAyNDQsImV4cCI6MjA2MDA4NjI0NH0.QQSD_cgs407vGxluHDFrqXpFq7nljnzdgEe4dsrTW_s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);